version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/public:/usr/src/app/public
      - ./frontend/src:/usr/src/app/src
      - ./frontend/tsconfig.json:/usr/src/app/tsconfig.json
